# Generated by Django 4.2.7 on 2026-01-21 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='部门代码')),
                ('description', models.TextField(blank=True, verbose_name='部门描述')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '禁用')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='岗位名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='岗位代码')),
                ('level', models.CharField(choices=[('junior', '初级'), ('mid', '中级'), ('senior', '高级'), ('expert', '专家')], default='mid', max_length=20, verbose_name='岗位级别')),
                ('responsibilities', models.TextField(blank=True, verbose_name='岗位职责')),
                ('requirements', models.TextField(blank=True, verbose_name='任职要求')),
                ('required_training_hours', models.IntegerField(default=40, verbose_name='要求培训时长(小时)')),
                ('min_experience', models.IntegerField(default=1, verbose_name='最低工作经验(年)')),
                ('min_education', models.CharField(choices=[('high_school', '高中'), ('college', '大专'), ('bachelor', '本科'), ('master', '硕士'), ('phd', '博士')], default='bachelor', max_length=50, verbose_name='最低学历')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '禁用')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='organization.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '岗位',
                'verbose_name_plural': '岗位',
                'db_table': 'positions',
            },
        ),
    ]
