# Generated by Django 4.2.7 on 2026-01-21 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='部门负责人'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.department', verbose_name='上级部门'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['department'], name='positions_departm_058a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['level'], name='positions_level_2c3dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['status'], name='positions_status_65369d_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent'], name='departments_parent__acf920_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['manager'], name='departments_manager_b4328a_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['status'], name='departments_status_e50229_idx'),
        ),
    ]
