# Generated by Django 4.2.7 on 2026-01-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='报表标题')),
                ('file_format', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF'), ('csv', 'CSV')], default='excel', max_length=20, verbose_name='文件格式')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='文件路径')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('parameters', models.JSONField(default=dict, verbose_name='报表参数')),
                ('status', models.CharField(choices=[('pending', '生成中'), ('completed', '已完成'), ('failed', '生成失败')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '生成的报表',
                'verbose_name_plural': '生成的报表',
                'db_table': 'generated_reports',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='模板代码')),
                ('report_type', models.CharField(choices=[('training_statistics', '培训统计报表'), ('exam_analysis', '考试分析报表'), ('competency_matrix', '能力矩阵报表'), ('compliance_report', '合规性报表'), ('user_activity', '用户活动报表')], max_length=50, verbose_name='报表类型')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('config', models.JSONField(default=dict, verbose_name='模板配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '报表模板',
                'verbose_name_plural': '报表模板',
                'db_table': 'report_templates',
            },
        ),
    ]
