# Generated by Django 4.2.7 on 2026-01-21 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='课程编号')),
                ('title', models.CharField(max_length=200, verbose_name='课程标题')),
                ('description', models.TextField(blank=True, verbose_name='课程描述')),
                ('course_type', models.CharField(choices=[('online', '在线课程'), ('offline', '线下培训'), ('mixed', '混合模式')], default='online', max_length=20, verbose_name='课程类型')),
                ('duration', models.IntegerField(default=60, verbose_name='课程时长(分钟)')),
                ('credit', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, verbose_name='学分')),
                ('passing_score', models.DecimalField(decimal_places=2, default=60.0, max_digits=5, verbose_name='及格分数')),
                ('instructor', models.CharField(blank=True, max_length=100, verbose_name='讲师')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/%Y/%m/', verbose_name='课程封面')),
                ('content_url', models.URLField(blank=True, verbose_name='课程内容链接')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='标签')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('enrollment_count', models.IntegerField(default=0, verbose_name='报名人数')),
                ('completion_count', models.IntegerField(default=0, verbose_name='完成人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='分类代码')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课程分类',
                'verbose_name_plural': '课程分类',
                'db_table': 'course_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='计划编号')),
                ('title', models.CharField(max_length=200, verbose_name='计划标题')),
                ('description', models.TextField(blank=True, verbose_name='计划描述')),
                ('plan_type', models.CharField(choices=[('individual', '个人计划'), ('department', '部门计划'), ('position', '岗位计划'), ('company', '公司计划')], default='department', max_length=20, verbose_name='计划类型')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('total_hours', models.IntegerField(default=0, verbose_name='总学时')),
                ('total_courses', models.IntegerField(default=0, verbose_name='课程数量')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('approval_comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '培训计划',
                'verbose_name_plural': '培训计划',
                'db_table': 'training_plans',
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '学习中'), ('completed', '已完成'), ('failed', '未通过'), ('exempted', '免修')], default='not_started', max_length=20, verbose_name='学习状态')),
                ('progress', models.IntegerField(default=0, verbose_name='学习进度(%)')),
                ('study_duration', models.IntegerField(default=0, verbose_name='学习时长(分钟)')),
                ('complete_date', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='考试成绩')),
                ('feedback', models.TextField(blank=True, verbose_name='学习反馈')),
                ('evaluation', models.TextField(blank=True, verbose_name='课程评价')),
                ('certificate_no', models.CharField(blank=True, max_length=100, verbose_name='证书编号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='training.course', verbose_name='课程')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='training.trainingplan', verbose_name='培训计划')),
            ],
            options={
                'verbose_name': '培训记录',
                'verbose_name_plural': '培训记录',
                'db_table': 'training_records',
            },
        ),
    ]
