# Generated by Django 4.2.7 on 2026-01-21 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0001_initial'),
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_training_plans', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='courses',
            field=models.ManyToManyField(related_name='training_plans', to='training.course', verbose_name='课程列表'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_training_plans', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='target_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to='organization.department', verbose_name='目标部门'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='target_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to='organization.position', verbose_name='目标岗位'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='target_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_training_plans', to=settings.AUTH_USER_MODEL, verbose_name='目标用户'),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='training.coursecategory', verbose_name='上级分类'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='training.coursecategory', verbose_name='课程分类'),
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='prerequisite_for', to='training.course', verbose_name='前置课程'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['user'], name='training_re_user_id_a94a81_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['course'], name='training_re_course__4060d8_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['plan'], name='training_re_plan_id_1d6470_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['status'], name='training_re_status_305681_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingrecord',
            unique_together={('user', 'course', 'plan')},
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['plan_type'], name='training_pl_plan_ty_b3ca7b_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['status'], name='training_pl_status_8fa00a_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['target_department'], name='training_pl_target__f831f8_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['target_position'], name='training_pl_target__be16a8_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['created_by'], name='training_pl_created_db4fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category'], name='courses_categor_2870c7_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='courses_status_67f368_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_type'], name='courses_course__f7418a_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_by'], name='courses_created_417ade_idx'),
        ),
    ]
