# Generated by Django 4.2.7 on 2026-01-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='考试编号')),
                ('title', models.CharField(max_length=200, verbose_name='考试标题')),
                ('exam_type', models.CharField(choices=[('practice', '练习'), ('formal', '正式考试'), ('makeup', '补考')], default='formal', max_length=20, verbose_name='考试类型')),
                ('total_questions', models.IntegerField(default=50, verbose_name='题目数量')),
                ('total_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='总分')),
                ('passing_score', models.DecimalField(decimal_places=2, default=60.0, max_digits=5, verbose_name='及格分数')),
                ('time_limit', models.IntegerField(default=60, verbose_name='考试时长(分钟)')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('max_attempts', models.IntegerField(default=1, verbose_name='最大尝试次数')),
                ('show_result', models.BooleanField(default=True, verbose_name='显示成绩')),
                ('show_answer', models.BooleanField(default=False, verbose_name='显示答案')),
                ('random_order', models.BooleanField(default=True, verbose_name='随机题目顺序')),
                ('shuffle_options', models.BooleanField(default=False, verbose_name='随机选项顺序')),
                ('description', models.TextField(blank=True, verbose_name='考试说明')),
                ('instructions', models.TextField(blank=True, verbose_name='考试须知')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('in_progress', '进行中'), ('completed', '已结束')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
                'db_table': 'exams',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('submitted', '已提交'), ('graded', '已评分')], default='not_started', max_length=20, verbose_name='状态')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='得分')),
                ('correct_count', models.IntegerField(default=0, verbose_name='答对题数')),
                ('wrong_count', models.IntegerField(default=0, verbose_name='答错题数')),
                ('is_passed', models.BooleanField(default=False, verbose_name='是否通过')),
                ('duration', models.IntegerField(default=0, verbose_name='用时(分钟)')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始答题时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='答案数据')),
                ('review_comment', models.TextField(blank=True, verbose_name='评语')),
                ('certificate_no', models.CharField(blank=True, max_length=100, verbose_name='证书编号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '考试成绩',
                'verbose_name_plural': '考试成绩',
                'db_table': 'exam_results',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single_choice', '单选题'), ('multiple_choice', '多选题'), ('true_false', '判断题'), ('fill_blank', '填空题'), ('short_answer', '简答题')], default='single_choice', max_length=20, verbose_name='题型')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='medium', max_length=20, verbose_name='难度')),
                ('title', models.TextField(verbose_name='题目')),
                ('content', models.TextField(blank=True, verbose_name='题目内容')),
                ('options', models.JSONField(blank=True, default=dict, verbose_name='选项')),
                ('correct_answer', models.JSONField(default=dict, verbose_name='正确答案')),
                ('explanation', models.TextField(blank=True, verbose_name='答案解析')),
                ('score', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='分值')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'questions',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='题库名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='题库代码')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='题库分类')),
                ('description', models.TextField(blank=True, verbose_name='题库描述')),
                ('question_count', models.IntegerField(default=0, verbose_name='题目数量')),
                ('total_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='总分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '题库',
                'db_table': 'question_banks',
            },
        ),
    ]
