# Generated by Django 4.2.7 on 2026-01-21 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examination', '0001_initial'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_question_banks', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_questions', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='examination.questionbank', verbose_name='所属题库'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='examination.exam', verbose_name='考试'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='training.course', verbose_name='关联课程'),
        ),
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='exam',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='exams', to=settings.AUTH_USER_MODEL, verbose_name='参与人员'),
        ),
        migrations.AddField(
            model_name='exam',
            name='question_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='examination.questionbank', verbose_name='题库'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_bank'], name='questions_questio_0adcb6_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='questions_questio_8af709_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='questions_difficu_8150ad_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam'], name='exam_result_exam_id_14ebd6_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['user'], name='exam_result_user_id_a6ed10_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['status'], name='exam_result_status_45d317_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['is_passed'], name='exam_result_is_pass_3bc8da_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['submitted_at'], name='exam_result_submitt_8c3a49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('exam', 'user')},
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['course'], name='exams_course__86c1c6_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['question_bank'], name='exams_questio_683e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_type'], name='exams_exam_ty_3674fc_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['status'], name='exams_status_863d01_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['start_time'], name='exams_start_t_bab18d_idx'),
        ),
    ]
