# Generated by Django 4.2.7 on 2026-01-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(blank=True, max_length=100, verbose_name='操作人姓名')),
                ('operator_username', models.CharField(blank=True, max_length=100, verbose_name='操作人用户名')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('login', '登录'), ('logout', '登出'), ('export', '导出'), ('import', '导入'), ('approve', '审批'), ('reject', '拒绝')], max_length=50, verbose_name='操作类型')),
                ('module', models.CharField(max_length=50, verbose_name='模块')),
                ('object_type', models.CharField(blank=True, max_length=50, verbose_name='对象类型')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='对象ID')),
                ('object_name', models.CharField(blank=True, max_length=200, verbose_name='对象名称')),
                ('description', models.TextField(blank=True, verbose_name='操作描述')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='请求方法')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='请求路径')),
                ('request_params', models.JSONField(blank=True, default=dict, verbose_name='请求参数')),
                ('response_result', models.JSONField(blank=True, default=dict, verbose_name='响应结果')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='success', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('response_time', models.IntegerField(default=0, verbose_name='响应时间(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'audit_logs',
            },
        ),
    ]
