# Generated by Django 4.2.7 on 2026-01-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='证书名称')),
                ('certificate_no', models.CharField(max_length=100, unique=True, verbose_name='证书编号')),
                ('issue_date', models.DateField(verbose_name='颁发日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('verification_code', models.CharField(max_length=50, unique=True, verbose_name='验证码')),
                ('status', models.CharField(choices=[('valid', '有效'), ('expired', '已过期'), ('revoked', '已吊销')], default='valid', max_length=20, verbose_name='状态')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/', verbose_name='证书文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '证书',
                'verbose_name_plural': '证书',
                'db_table': 'certificates',
            },
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='能力名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='能力代码')),
                ('description', models.TextField(blank=True, verbose_name='能力描述')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='能力分类')),
                ('level', models.CharField(choices=[('aware', '了解'), ('proficient', '掌握'), ('skilled', '熟练'), ('master', '精通')], default='proficient', max_length=20, verbose_name='能力级别')),
                ('assessment_method', models.CharField(choices=[('exam', '考试'), ('evaluation', '评估'), ('certification', '认证'), ('practical', '实操')], default='exam', max_length=20, verbose_name='评估方式')),
                ('required', models.BooleanField(default=True, verbose_name='是否必需')),
                ('passing_score', models.DecimalField(decimal_places=2, default=60.0, max_digits=5, verbose_name='达标分数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '能力',
                'verbose_name_plural': '能力',
                'db_table': 'competencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, choices=[('aware', '了解'), ('proficient', '掌握'), ('skilled', '熟练'), ('master', '精通')], max_length=20, null=True, verbose_name='评估级别')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='评估分数')),
                ('status', models.CharField(choices=[('pending', '待评估'), ('in_progress', '评估中'), ('completed', '已完成'), ('approved', '已审批'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='评估状态')),
                ('evidence', models.TextField(blank=True, verbose_name='能力证明')),
                ('assessor_comment', models.TextField(blank=True, verbose_name='评估意见')),
                ('assessed_at', models.DateTimeField(blank=True, null=True, verbose_name='评估时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '能力评估',
                'verbose_name_plural': '能力评估',
                'db_table': 'competency_assessments',
            },
        ),
    ]
