# Generated by Django 4.2.7 on 2026-01-21 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examination', '0001_initial'),
        ('training', '0001_initial'),
        ('organization', '0001_initial'),
        ('competency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competencyassessment',
            name='assessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_assessments', to=settings.AUTH_USER_MODEL, verbose_name='评估人'),
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='competency.competency', verbose_name='能力'),
        ),
        migrations.AddField(
            model_name='competencyassessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_assessments', to=settings.AUTH_USER_MODEL, verbose_name='被评估人'),
        ),
        migrations.AddField(
            model_name='competency',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_competencies', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='competency',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='competency.competency', verbose_name='上级能力'),
        ),
        migrations.AddField(
            model_name='competency',
            name='related_courses',
            field=models.ManyToManyField(blank=True, related_name='related_competencies', to='training.course', verbose_name='关联课程'),
        ),
        migrations.AddField(
            model_name='competency',
            name='related_positions',
            field=models.ManyToManyField(blank=True, related_name='required_competencies', to='organization.position', verbose_name='关联岗位'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='competency.competencyassessment', verbose_name='关联评估'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='competency.competency', verbose_name='关联能力'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='exam_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='examination.examresult', verbose_name='关联考试成绩'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL, verbose_name='颁发人'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='持有人'),
        ),
        migrations.AddIndex(
            model_name='competencyassessment',
            index=models.Index(fields=['user'], name='competency__user_id_430ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='competencyassessment',
            index=models.Index(fields=['competency'], name='competency__compete_dba74a_idx'),
        ),
        migrations.AddIndex(
            model_name='competencyassessment',
            index=models.Index(fields=['assessor'], name='competency__assesso_400efa_idx'),
        ),
        migrations.AddIndex(
            model_name='competencyassessment',
            index=models.Index(fields=['status'], name='competency__status_e7a5e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='competencyassessment',
            unique_together={('user', 'competency')},
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['user'], name='certificate_user_id_bd0e56_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['competency'], name='certificate_compete_1058f5_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['status'], name='certificate_status_a01db5_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_no'], name='certificate_certifi_63d820_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['verification_code'], name='certificate_verific_8df4b9_idx'),
        ),
    ]
